### ISSUE TITLE
Add Travis CI to xarray_filters repo

### ISSUE THREAD

**Issue by PeterDSteinberg** [ContinuumIO/xarray_filters#4]
* [x] Use `earthio` as guidance on how to do Travis CI for several versions of Python and upload packages to the `dev` label of the `elm` anaconda user. 
  * [x] Modify `.travis.yml` as needed
  * [x] Do Travis CI config in Github UI

@gbrener can clarify any setup questions (he set up `elm` and `earthio`'s CI)

**Comment by PeterDSteinberg** [comment]
Fixed by #3

**Comment by gbrener** [comment]
Hey @PeterDSteinberg , I believe this is finished but the tests do not currently pass. The infrastructure piece should be done, however. I simplified things a bit (in the interest of time) to just use the `.travis.yml` file instead of a bash script - happy to change this to conform more closely with elm/earthio, however.

**Comment by PeterDSteinberg** [comment]
@gbrener Using .travis.yml alone sounds good - I'll close this issue as this CI tests are working and finding actual doctest failures in assertions.
